-- Create tables for the Furniture Marketplace App

-- 1. Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    category TEXT,
    image TEXT,
    location TEXT,
    aspect TEXT,
    rating NUMERIC(3, 1) DEFAULT 0,
    reviews_count INTEGER DEFAULT 0,
    is_new BOOLEAN DEFAULT FALSE,
    is_new BOOLEAN DEFAULT FALSE,
    description TEXT,
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Favorites Table
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- 3. Profiles Table (Optional, for extra user info like avatar)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Enable Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Products (Everyone can view)
CREATE POLICY "Public products are viewable by everyone." ON products FOR SELECT USING (true);

-- Policies for Favorites (Users can only see/edit their own)
CREATE POLICY "Users can view their own favorites." ON favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own favorites." ON favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own favorites." ON favorites FOR DELETE USING (auth.uid() = user_id);

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Insert Dummy Data for Products
INSERT INTO products (title, price, category, image, location, aspect, rating, reviews_count, is_new) VALUES
('1970s Velvet Sofa', 450.00, 'sofas', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_7CdCHlYZUxXinXnnjQHnTkP3fadL1tXiU0Oa_e5RenGOinu8N3_rGY1BqgmqANZdrxiBNIxCTDXrKt3hjjt155D1_RwGgB3HuisKKSRk1JZgOFRWBW9BBt_hE-MLSAPjSwMqmMQaxEvWsu9n8b8ZaGlRI9BzFJuk_h-W76FR9COf6Tt3Ha-_a3hfBvBxMPVgU6Nabdk55UE5pdlM0AC_uqSUgGfooV_4U0I0fP1dVX5p0mFjRIm_gstDlSUPFjy62rQB4lZHovNP', 'Brooklyn, NY', '3/4', 4.8, 124, true),
('Oak Coffee Table', 120.00, 'tables', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRk6ZkMR7el4beJA8EILmTZr97kl-B3chhZ9H6DiBfcqL8KlB9KUhURhiU9lBVwR0y93TKJfTOaMtnLWpSPajFWB0ORqHdaQldebmOsy4nCjFzpoOkdalCqvFqN90rdx6KJfDZZ20YBpN3GI7HF4YsEpFcW9_k4LL0L2FAZjk8CsjoboPMWj27VPIE-A7Hq65JIkEiiDCU2oORJhzI4I5fMYhqTYPa-WcIOvs36N1yejZkb24AO-y7oQNZ5DaV8PxpoFKwJELknBt5', 'Austin, TX', '1/1', 4.5, 89, false),
('Industrial Lamp', 45.00, 'lighting', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiHEDozq89TyD9zpm9DAO9eEPUjKnTJl97HuP4jdeC2lP27Cc1sZIzzhG9d6yl5mF9NuyhXLtqm7yU97nwoSM1NG75h5S7LhaCxvGvXlnhvYkF0ujVB2Ktb4y6qWZvVVE6R0BmqmdZy3dcsS9UaRwc2bz5z74qSpxRXHDmWf5iY76KSIAllmPvF1mc8faHL31E3n_cV8eOHGu6lV6x2y9U7MZsmGEtt9s4W8G6yR8Zz2oelpHerqal_hoUyQP6o9YaHpFWcFZbSRvK', 'Portland, OR', '3/5', 4.7, 215, false),
('Danish Armchair', 280.00, 'sofas', 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6S7b0zkYnUVsvWGjOMjnrrHGDKpXiDi00ALcCvzdC5Fe4ycpiOWdmRTW3VyQKX6qcVkIJ84NQOjXuhdnxe40UV6R3dMHqIK1yKe9exqJqjVDl-vf93VBcGoF9ARhh3vEq2626tU8FSFM4gHjL1tb6aJbdDyKlSecDWL8irPyEwEhD3DZfQWns47oR0KAIXJEImNP0lqOkIdGvdR-vstaMWkyMlg4c72uUEpGzDlrmIMcIWYxeW3syb-8GFtBBbYaoFC1tt2Z6HJ8k', 'Seattle, WA', '4/5', 4.9, 56, true),
('Large Monstera', 35.00, 'plants', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjQh1gVJn_V3FJth3MUfKkh6EnWoiNcBByDF1U9FxUWXMK_IG01wwHI1FzIXiKPsqDFU2qYFcre_02CTisEU7nzVMJCSH9_twhNgk0rXLGy96or8u2il8TfKtq452mLBb5ZLIFJklHQPq0LgxrkKPKLh9Dp-SVRI8UenzpjRvMxt5ReAGP7IkmpT__r8Fr-YRlgfhvUBNzTln_km1KfYRzuUQolI7sYyl2c2H4CCSJXeNfb6Dd4i72rSreLybk3ljjHulWki8S-ygM', 'Los Angeles, CA', '1/1', 4.8, 42, false),
('Teak Bookshelf', 150.00, 'shelves', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOCuicokfWi5DEcsTTXHxars9-hAmFIuCGAyuLi5goXG1L_SL0tMTsKTSqm2JK1w0Id4POEkgFON71Gq1NfqbD8dQh-pzJTyuw9TvRjpU71sYn1QP-mGo5EUGQqtzB9VyMRlX93Ua5NRLzK-KEzGGkUb1PTzeMjSL7wx7PCBi5rkaZvWKYQ1qU3Ose9sXDNO4K2jf2_u5dGUriA1OISMdk3dbQ_p_eZu-040A94AkYOpi718qr7OEJrLOgqUYCu4VkA-UeqOrhW8Y9', 'Chicago, IL', '3/4', 4.6, 75, false);

-- Storage Setup for Product Images
-- 1. Create Bucket
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- 2. Storage Policies (Adjust as needed for strictness)
-- Allow Public Read
create policy "Public Access" 
on storage.objects for select 
using ( bucket_id = 'product-images' );

-- Allow Authenticated Upload
create policy "Authenticated Upload" 
on storage.objects for insert 
with check ( bucket_id = 'product-images' AND auth.role() = 'authenticated' );

-- Allow Owner Delete (Optional, simplified)
create policy "Owner Delete" 
on storage.objects for delete 
using ( bucket_id = 'product-images' AND auth.uid() = owner );

-- Migrations for existing tables (in case table already exists without these)
ALTER TABLE products ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- Policies for Products
-- Ensure RLS is enabled
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Drop existing generic select policy to be safe/clean re-run (optional, or rely on distinct names)
DROP POLICY IF EXISTS "Public products are viewable by everyone." ON products;
CREATE POLICY "Public products are viewable by everyone." ON products FOR SELECT USING (true);

-- Allow authenticated users to insert products linked to their ID
DROP POLICY IF EXISTS "Users can create products." ON products;
CREATE POLICY "Users can create products." ON products FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Allow users to update/delete their own products
DROP POLICY IF EXISTS "Users can update own products." ON products;
CREATE POLICY "Users can update own products." ON products FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own products." ON products;
CREATE POLICY "Users can delete own products." ON products FOR DELETE USING (auth.uid() = user_id);

-- Migration: Add tags column if it doesn't exist (safe re-run)
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';


-- 4. SEARCH FUNCTION (PostgreSQL RPC)
-- This function allows searching across multiple columns (title, description, tags)
CREATE OR REPLACE FUNCTION search_products(keyword text)
RETURNS SETOF products AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM products
    WHERE 
      title ILIKE '%' || keyword || '%' OR
      description ILIKE '%' || keyword || '%' OR
      keyword = ANY(tags) OR
      EXISTS (
        SELECT 1 
        FROM unnest(tags) tag 
        WHERE tag ILIKE '%' || keyword || '%'
      );
END;
$$ LANGUAGE plpgsql;
